"use client"
//use clientならaccordionが動く

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
//fontawesomeが巨大化するのを防ぐ設定
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

import { Providers } from "./providers";
import { Button } from '@nextui-org/button';
import { Accordion } from '@nextui-org/accordion';
import { AccordionItem } from '@nextui-org/accordion';
import { faCode } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faFaceSmile, faMessage } from '@fortawesome/free-regular-svg-icons'
import { LayoutProps } from '../.next/types/app/layout';
import Image from 'next/image';
import { Divider, Listbox, ListboxItem, ScrollShadow, Spacer, User } from '@nextui-org/react'
import { faCreativeCommonsNd } from '@fortawesome/free-brands-svg-icons'
import { faSquareXTwitter } from '@fortawesome/free-brands-svg-icons/faSquareXTwitter'
import { faSquareGithub } from '@fortawesome/free-brands-svg-icons/faSquareGithub'


//use clientのときはMetadataの定義をコメント必要
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const iconSize = 35;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    // ここの階層を崩すとホットリロードがただしく動作しなくなる。
    <html lang="en" className='dark'>
      <head>
      </head>
      <body className={inter.className}>
        <Providers>
          {/* リストボックスで大きさそろえる */}
          {/* マウスオンでアニメーションさせたい}
          {/* メイン画面が下の方に行ってしまうのでその修正 */}
          {/* accordion展開するとヘッダーずれるので修正 */}
          {/* カードレイアウトにするのいいかも accordionメニューもやめてそれがいいかもしれない */}
          <header className=''>
          </header>
          <div className='flex flex-row bg-gray-700'>

            {/* sidebar */}
            <div className='w-64 h-screen bg-gradient-to-r from-slate-900'>
              <ScrollShadow hideScrollBar className="h-full">
                <nav className=''>
                  <p>
                    Orukred
                  </p>
                  <User
                    name=""
                    avatarProps={{
                      isBordered: true,
                      radius: "full",
                      src: "/orukred_icon.png",
                      size: "lg",
                      className: "w-32 h-32"
                    }}
                  />
                  <div className="flex space-x-2">
                    <Image src={'/icon/github/github-mark-white.svg'} alt={'GitHub'} width={iconSize} height={iconSize} />
                    <Image src={'/icon/x/logo.svg'} alt={'X'} width={iconSize} height={iconSize} />
                    <Image src={'/icon/qiita/qiita.png'} alt={'Qiita'} width={iconSize} height={iconSize} />
                    <Image src={'/icon/zenn/logo-only.svg'} alt={'Zenn'} width={iconSize} height={iconSize} />
                  </div>
                  <Spacer y={5} />
                  <ul>
                    <li>
                      <span className='i-lucide-cat'>
                        <FontAwesomeIcon icon={faFaceSmile} />
                        <a href="#introduction">
                          About
                        </a>
                      </span>
                    </li>
                    <li>
                      <FontAwesomeIcon icon={faMessage} />
                      <a href="#contact">
                        Contact
                      </a>
                    </li>
                    <li>
                      <Accordion>
                        <AccordionItem key="1" aria-label="Accordion 1" title="Programs" startContent={<FontAwesomeIcon icon={faCode} />}>
                          <ul>
                            <li>
                              <a>
                                TyranoScript_syntax
                              </a>
                            </li>
                            <li>
                              <a>
                                ここはお前のチラシ裏
                              </a>
                            </li>
                            <li>
                              <a>
                                ポートフィリオ
                              </a>
                            </li>
                          </ul>
                        </AccordionItem>
                      </Accordion>
                    </li>
                    <li>
                      <FontAwesomeIcon icon={faCreativeCommonsNd} />
                      works
                    </li>
                  </ul>
                </nav>
              </ScrollShadow>
            </div>

            {/* メインコンテンツ */}
            <main className='flex-grow p-4'>
              {/* children　でpageの中身表示 */}
              {children}
              <section id="introduction">
                自己紹介の内容
              </section>

              <section id="programs">
                プログラム作品のリスト
                <ul>
                  ここに作品
                </ul>
              </section>
              <section id="contact">
                コンタクトの内容
              </section>
              <section id="works">
                <ul>
                  お仕事一覧
                </ul>
              </section>
            </main>


          </div>





        </Providers>
      </body>
    </html>
  )
}

